### ISSUE TITLE
Gameplay report

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [totine/java-academy--tic-tac-toe#12]
Interesting approach, to have 'shortcuts' to get to various states. I can't however verify that all states are in since game crashes with NPE

**Comment by LIttleAncientForestKami** [comment]
➜  target ±:(master) java -jar xoGame-1.0.jar                                        [% 11:43:18]
To jest początek rundy
Wpisz cokolwiek, aby rozpocząć rundę (tu będą ustawienia rundy)
cpś
akademia.ox.Board@4783da3fRunda jest w trakcie teraz X
Wpisz victory, jeśli ma być zwycięstwo; Wpisz draw jeśli ma być remis, wpisz exit, aby zakończyć rundę 'walkowerem', wpisz cokolwiek, aby kontynuować rozgrywkę
draw
Jest remis
Wpisz cokolwiek, aby przejść do podsumowania

Runda zakończona
Wpisz end, aby zakończyć grę, wpisz continue, aby kontynować
continue
To jest początek rundy
Wpisz cokolwiek, aby rozpocząć rundę (tu będą ustawienia rundy)
a
Exception in thread "main" java.lang.NullPointerException
	at akademia.ox.states.InProgressState.showCurrentPlayer(InProgressState.java:54)
	at akademia.ox.states.InProgressState.showStateInfo(InProgressState.java:27)
	at akademia.ox.Main.main(Main.java:21)
➜  target ±:(master) java -jar xoGame-1.0.jar                                        [% 11:43:45]
To jest początek rundy
Wpisz cokolwiek, aby rozpocząć rundę (tu będą ustawienia rundy)
a
akademia.ox.Board@4783da3fRunda jest w trakcie teraz X
Wpisz victory, jeśli ma być zwycięstwo; Wpisz draw jeśli ma być remis, wpisz exit, aby zakończyć rundę 'walkowerem', wpisz cokolwiek, aby kontynuować rozgrywkę
victory
ZWYCIĘSTWO wygrał X(p1)
Wpisz cokolwiek, aby przejsć do podsumowania
a
Runda zakończona
Wpisz end, aby zakończyć grę, wpisz continue, aby kontynować
continue
To jest początek rundy
Wpisz cokolwiek, aby rozpocząć rundę (tu będą ustawienia rundy)
s
Exception in thread "main" java.lang.NullPointerException
	at akademia.ox.states.InProgressState.showCurrentPlayer(InProgressState.java:54)
	at akademia.ox.states.InProgressState.showStateInfo(InProgressState.java:27)
	at akademia.ox.Main.main(Main.java:21)
