### ISSUE TITLE
java.util.IllegalFormatConversionException

### ISSUE THREAD

**Issue by boczkas** [totine/java-academy--tic-tac-toe#19]
Configuration: 5 5 3
Entry sequence:  1, 2, 3, 4, 5, 1

Leads to:
Exception in thread "main" java.util.IllegalFormatConversionException: d != java.lang.String
	at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4331)
	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2846)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2800)
	at java.base/java.util.Formatter.format(Formatter.java:2581)
	at java.base/java.util.Formatter.format(Formatter.java:2517)
	at java.base/java.lang.String.format(String.java:2747)
	at akademia.ox.states.InProgressState.consumeInput(InProgressState.java:66)
	at akademia.ox.game.OxGame.loop(OxGame.java:52)
	at akademia.ox.game.OxGame.start(OxGame.java:60)
	at akademia.ox.Main.main(Main.java:17)

**Comment by totine** [comment]
Fixed
