### ISSUE TITLE
Number format exception

### ISSUE THREAD

**Issue by boczkas** [totine/java-academy--tic-tac-toe#21]
This is the beginning of round no. 1
```
Type game settings in format x y k, where x is for board rows, y - for board columns, k - for wining condition (k must be less or equal than smaller value of x and y) 
x and y must be between 3 and 100
For example: 4 5 3 
or press ENTER to play standard OX game with 3x3 board"
111111111 11111111111111111 5
Exception in thread "main" java.lang.NumberFormatException: For input string: "11111111111111111"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.IntPipeline.toArray(IntPipeline.java:516)
	at akademia.ox.game.OxRound.createGameFromQuery(OxRound.java:29)
	at akademia.ox.states.InitialState.setNextStateBasedOnInputQuery(InitialState.java:56)
	at akademia.ox.states.InitialState.consumeInput(InitialState.java:47)
	at akademia.ox.game.OxGame.loop(OxGame.java:52)
	at akademia.ox.game.OxGame.start(OxGame.java:60)
	at akademia.ox.Main.main(Main.java:17)

**Comment by totine** [comment]
Obsłużone
