### ISSUE TITLE
Another null pointer

### ISSUE THREAD

**Issue by boczkas** [totine/java-academy--tic-tac-toe#24]
```To jest początek rundy 1

Wpisz ustawienia gry w postaci x y k, gdzie x to ilość rzędów planszy, y - ilość kolumn planszy, k - długość linii niezbędna do wygranej (nie może być większa niż mniejsza z liczb x lub y) 
x i y mają zawierać się między 3 a 100
Przykładowy wypis: 4 5 3 
lub naciśnij enter, aby wybrać ustawienia standardowe - plansza 3x3 z linią 3"
200000 2000000 20

Exception in thread "main" java.lang.NullPointerException
	at akademia.ox.states.InProgressState.showStateInfo(InProgressState.java:38)
	at akademia.ox.game.OxGame.loop(OxGame.java:53)
	at akademia.ox.game.OxGame.start(OxGame.java:33)
	at akademia.ox.Main.main(Main.java:20)

**Comment by totine** [comment]
fixed
